### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by ObedH26** [DavideGalilei/gpytranslate#22] opened 2022-02-27 19:55 UTC
### What happened?

Hello hello im getting this error;JSONDecodeError('Expecting value: line 1 column 1 (char 0)'). My script worked once or twice and then im getting this every time ever since, i dont get what is going on would be nice if you can help me , thanks have a great day

### OS / Environment

Iphone X ios 14.6, jupyter lab 

### Traceback

```python-traceback
---------------------------------------------------------------------------
TranslationError                          Traceback (most recent call last)
Input In [7], in <module>
     22         print(f"Translation: {translation.text}\nDetected language: {language}\n\n")
     25 if __name__ == "__main__":
---> 26     asyncio.run(main("mer"))

File /private/var/containers/Bundle/Application/99EF6119-3B0D-40F0-8B62-4976D61AB3FD/Carnets.app/Library/lib/python3.9/site-packages/nest_asyncio.py:38, in _patch_asyncio.<locals>.run(main, debug)
     36 task = asyncio.ensure_future(main)
     37 try:
---> 38     return loop.run_until_complete(task)
     39 finally:
     40     if not task.done():

File /private/var/containers/Bundle/Application/99EF6119-3B0D-40F0-8B62-4976D61AB3FD/Carnets.app/Library/lib/python3.9/site-packages/nest_asyncio.py:81, in _patch_loop.<locals>.run_until_complete(self, future)
     78 if not f.done():
     79     raise RuntimeError(
     80         'Event loop stopped before Future completed.')
---> 81 return f.result()

File /private/var/containers/Bundle/Application/99EF6119-3B0D-40F0-8B62-4976D61AB3FD/Carnets.app/Library/lib/python3.9/asyncio/futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception
    202 return self._result

File /private/var/containers/Bundle/Application/99EF6119-3B0D-40F0-8B62-4976D61AB3FD/Carnets.app/Library/lib/python3.9/asyncio/tasks.py:256, in Task.__step(***failed resolving arguments***)
    252 try:
    253     if exc is None:
    254         # We use the `send` method directly, because coroutines
    255         # don't have `__iter__` and `__next__` methods.
--> 256         result = coro.send(None)
    257     else:
    258         result = coro.throw(exc)

Input In [7], in main(mot)
     18 print(word)
     19 print(type(word))
---> 20 translation = await t.translate(str(word), targetlang="fr")
     21 language = await t.detect(translation.text)
     22 print(f"Translation: {translation.text}\nDetected language: {language}\n\n")

File /var/mobile/Containers/Data/Application/24595BCF-2FB7-4B88-8C4D-4852824A51D5/Library/lib/python3.9/site-packages/gpytranslate/gpytranslate.py:157, in Translator.translate(self, text, sourcelang, targetlang, client, dt, dj, **extra)
    155     return self.check(raw=raw, client=client, dt=dt, text=text)
    156 except Exception as e:
--> 157     raise TranslationError(e) from None

TranslationError: An error occurred while trying to translate/tts: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

In [ ]:
```

### Searched before submitting

- [X] I searched for duplicates, and didn't found anything.
- [X] I searched this bug on a search engine, and didn't found anything.

**Comment by DavideGalilei** [comment] 2022-02-27 20:04
Duplicate of #20

**Comment by DavideGalilei** [comment] 2022-02-27 20:05
This is due to Google rate limiting your requests. Likely you sent a lot of requests in a short while

**Comment by ObedH26** [comment] 2022-02-28 11:14
Oh okay i see,i read the #20 am i right if i say i will need lot of proxy if i want to translate a huge list of word ?I don't know a lot about proxy and my english understanding isn't that good too. 
Actually i wonder if there isn't 'an other way'? im asking because im using deep_translator package often and i can translate tens of thousands in a while without an api code and i guess the owner dont pay one for all his guest lol maybe something interesting to take there i dont know.
Also im sorry seem like i dont know how to use github i thought i was the first guy to post an issues 😅

**Comment by DavideGalilei** [comment] 2022-02-28 19:25
> May i ask you if you know about why other translators package dont use to give limit on request ?

I don't know, it depends by how requests are handled by the library and which Google Translate API endpoint they use. I can't provide an answer for that, as the question is too broad

**Comment by ObedH26** [comment] 2022-03-01 23:11
Ah okay i see, i dont have knowledge about these thing for now at least i can't understand more than this, good continuation on your work also good luck thanks for helping me

**Closed** 2022-03-01 23:11 UTC
Labels: bug
